name: Deploy to aws

# AWS CREDENTIALS
env:
  AWS_REGION_NAME: "<aws_region_name>"
  PACKAGE_NAME: "<aws_package_name>"
  S3_BUCKET_NAME: "<bucket_name>"

# Create deployment when we push code on deploy branch
on:
  push:
    branches:
      - deploy

jobs:
  deploy-app-aws:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkou code
        uses: actions/checkout@v3

      - name: Create ZIP 
        run: zip -r ${{ env.PACKAGE_NAME }} ./ -x *.git*

      - name: Configure aws
        uses: aws-actions/configure-aws-redentials@v1
        with:
          aws-acces-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRETS_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION_NAME}}

      - name: Move deployment package to s3 bucket
        run: aws s3 cp {{env.PACKAGE_NAME}} s3://{{env.S3_BUCKET_NAME}}